import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { cookies } from "next/headers"; 
import { ThemeToggle } from "@/components/ThemeToggle";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "RnG solutions",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const cookieStore = await cookies();
  const theme = cookieStore?.get('theme');

  return (
    <html lang="en" data-theme={theme?.value}>
      <body
        
      >
        <ThemeToggle initialValue={theme?.value as ('light' | 'dark')} />
        {children}
      </body>
    </html>
  );
}
